INSERT INTO DEPARTAMENTO(NOME)
VALUES ('CONTÁBIL');
INSERT INTO DEPARTAMENTO(NOME)
VALUES ('RH');
INSERT INTO DEPARTAMENTO(NOME)
VALUES ('MARKETING');
INSERT INTO DEPARTAMENTO(NOME)
VALUES ('TI');
INSERT INTO DEPARTAMENTO(NOME)
VALUES ('ALMOXARIFADO');
INSERT INTO DEPARTAMENTO(NOME)
VALUES ('ESTOQUE');
INSERT INTO DEPARTAMENTO(NOME)
VALUES ('VENDAS');
INSERT INTO DEPARTAMENTO(NOME)
VALUES ('GERÊNCIA');

INSERT INTO FUNCIONARIO (NOME, CPF, EMAIL, DATA_NASCIMENTO, ATIVO, SEXO, SALARIO, CIDADE, UF, COD_DEPARTAMENTO)
VALUES ('Heitor Marcos Campos ', '51595506829', 'heitormarcoscampos_@pontofinalcafe.com.br ', '1985-09-17', 1, 'M',
        1560, 'Taquaritinga', 'SP', 1);
INSERT INTO FUNCIONARIO (NOME, CPF, EMAIL, DATA_NASCIMENTO, ATIVO, SEXO, SALARIO, CIDADE, UF, COD_DEPARTAMENTO)
VALUES ('Antonio Yuri Otávio Souza ', '05092502894', 'antonioyuriotaviosouza@pmm.am.v.br ', '1955-09-22', 1, 'M', 1560,
        'Taquaritinga', 'SP', 1);
    INSERT
INTO FUNCIONARIO (NOME, CPF, EMAIL, DATA_NASCIMENTO, ATIVO, SEXO, SALARIO, CIDADE, UF, COD_DEPARTAMENTO)
VALUES ('Dio Lorenzo Luís Cavalcanti ', '30094943869', 'diolorenzoluiscavalcanti@bessa.net.br ', '1945-12-06', 1, 'M', 1999, 'Taquaritinga', 'SP', 1);
INSERT INTO FUNCIONARIO (NOME, CPF, EMAIL, DATA_NASCIMENTO, ATIVO, SEXO, SALARIO, CIDADE, UF, COD_DEPARTAMENTO)
VALUES ('Tia Eduardo Otávio Corte Real ', '20002668866', 'ttiaeduardootaviocortereal@outlock.com ', '1955-02-18', 1, 'M', 1400, 'Taquaritinga', 'SP', 1);
INSERT INTO FUNCIONARIO (NOME, CPF, EMAIL, DATA_NASCIMENTO, ATIVO, SEXO, SALARIO, CIDADE, UF, COD_DEPARTAMENTO)
VALUES ('Nina Flávia Melo ', '15477014806', 'ninaflaviamelo-83@freitasepozzatti.com.br ', '1965-09-10', 1, 'F', 1530, 'Taquaritinga', 'SP', 1);
INSERT INTO FUNCIONARIO (NOME, CPF, EMAIL, DATA_NASCIMENTO, ATIVO, SEXO, SALARIO, CIDADE, UF, COD_DEPARTAMENTO)
VALUES ('Sandra Mirella Débora Moreira ', '41595690808', 'sandramirelladeboramoreira@raposoengenharia.com.br ', '1982-02-21', 1, 'F', 1358, 'Taquaritinga', 'SP', 2);
INSERT INTO FUNCIONARIO (NOME, CPF, EMAIL, DATA_NASCIMENTO, ATIVO, SEXO, SALARIO, CIDADE, UF, COD_DEPARTAMENTO)
VALUES ('Sebastiana Marcela Melo ', '29246188861', 'sebastianamarcelamelo_@orteca.com.br ', '1983-09-03', 1, 'F', 4800, 'Taquaritinga', 'SP', 2);
INSERT INTO FUNCIONARIO (NOME, CPF, EMAIL, DATA_NASCIMENTO, ATIVO, SEXO, SALARIO, CIDADE, UF, COD_DEPARTAMENTO)
VALUES ('Rafaela Esther Nogueira ', '68704015860', 'rafaelaesthernogueira_@mantegassi.com ', '1943-05-17', 1, 'F', 1560, 'Taquaritinga', 'SP', 2);
INSERT INTO FUNCIONARIO (NOME, CPF, EMAIL, DATA_NASCIMENTO, ATIVO, SEXO, SALARIO, CIDADE, UF, COD_DEPARTAMENTO)
VALUES ('Carolina Alice Vitória dos Santos ', '44941568842', 'carolinaalicevitoriadossantos_@domain.com.br ', '1973-02-19', 1, 'F', 2500, 'Taquaritinga', 'SP', 2);
INSERT INTO FUNCIONARIO (NOME, CPF, EMAIL, DATA_NASCIMENTO, ATIVO, SEXO, SALARIO, CIDADE, UF, COD_DEPARTAMENTO)
VALUES ('Yuri Juan Fogaça ', '22258750814', 'yurijuanfogaca@policiacivil.sp.v.br ', '1970-02-19', 1, 'M', 1560, 'Matão', 'SP', 2);
INSERT INTO FUNCIONARIO (NOME, CPF, EMAIL, DATA_NASCIMENTO, ATIVO, SEXO, SALARIO, CIDADE, UF, COD_DEPARTAMENTO)
VALUES ('Nina Evelyn Mariana Aparício ', '06964234802', 'marianaaparicio@centrooleo.com.br ', '1991-04-19', 1, 'F', 1112, 'Matão', 'SP', 3);
INSERT INTO FUNCIONARIO (NOME, CPF, EMAIL, DATA_NASCIMENTO, ATIVO, SEXO, SALARIO, CIDADE, UF, COD_DEPARTAMENTO)
VALUES ('Henry Hu Rodrigues ', '13858110809', 'henryhurodrigues-81@a.com ', '1926-05-19', 1, 'M', 1560, 'Matão', 'SP', 3);
INSERT INTO FUNCIONARIO (NOME, CPF, EMAIL, DATA_NASCIMENTO, ATIVO, SEXO, SALARIO, CIDADE, UF, COD_DEPARTAMENTO)
VALUES ('Eduardo Ruan Monteiro ', '51787017800', 'eduardoruanmonteiro@sorocaba.com ', '1942-04-19', 1, 'M', 2500, 'Matão', 'SP', 3);
INSERT INTO FUNCIONARIO (NOME, CPF, EMAIL, DATA_NASCIMENTO, ATIVO, SEXO, SALARIO, CIDADE, UF, COD_DEPARTAMENTO)
VALUES ('Mário Davi de Paula ', '85327210871', 'mariodavidepaula-90@allianceconsultoria.com.br ', '1951-06-19', 1, 'M', 1560, 'Matão', 'SP', 3);
INSERT INTO FUNCIONARIO (NOME, CPF, EMAIL, DATA_NASCIMENTO, ATIVO, SEXO, SALARIO, CIDADE, UF, COD_DEPARTAMENTO)
VALUES ('Aline Analu Ribeiro ', '97251185881', 'alineanaluribeiro@artelazer.com ', '1964-07-19', 1, 'F', 1560, 'Jaboticabal', 'SP', 3);
INSERT INTO FUNCIONARIO (NOME, CPF, EMAIL, DATA_NASCIMENTO, ATIVO, SEXO, SALARIO, CIDADE, UF, COD_DEPARTAMENTO)
VALUES ('Olivia Aparecida Allana Silva ', '59073737842', 'oliviaaparecidaallanasilva@bluewash.com.br ', '1976-08-19', 1, 'M', 1560, 'Jaboticabal', 'SP', 3);
INSERT INTO FUNCIONARIO (NOME, CPF, EMAIL, DATA_NASCIMENTO, ATIVO, SEXO, SALARIO, CIDADE, UF, COD_DEPARTAMENTO)
VALUES ('Sarah Lara Laura de Paula ', '03797855877', '.sarahlaralauradepaula@callan.com.br ', '1965-09-19', 1, 'F', 3540, 'Jaboticabal', 'SP', 4);
INSERT INTO FUNCIONARIO (NOME, CPF, EMAIL, DATA_NASCIMENTO, ATIVO, SEXO, SALARIO, CIDADE, UF, COD_DEPARTAMENTO)
VALUES ('Aurora Luzia Vitória Almeida ', '91162200804', 'aauroraluziavitoriaalmeida@ruilacos.com.br ', '1964-10-19', 1, 'F', 1560, 'Jaboticabal', 'SP', 4);
INSERT INTO FUNCIONARIO (NOME, CPF, EMAIL, DATA_NASCIMENTO, ATIVO, SEXO, SALARIO, CIDADE, UF, COD_DEPARTAMENTO)
VALUES ('Anthony Arthur Corte Real ', '68615701849', 'anthonyarthurcortereal_@hotmail.co.jp ', '1939-11-19', 1, 'M', 1560, 'Jaboticabal', 'SP', 4);
INSERT INTO FUNCIONARIO (NOME, CPF, EMAIL, DATA_NASCIMENTO, ATIVO, SEXO, SALARIO, CIDADE, UF, COD_DEPARTAMENTO)
VALUES ('Manuela Sara Almeida ', '07067042828', 'manuelasaraalmeida@telefonica.com ', '1986-12-19', 1, 'F', 2560, 'Monte Alto', 'SP', 4);
INSERT INTO FUNCIONARIO (NOME, CPF, EMAIL, DATA_NASCIMENTO, ATIVO, SEXO, SALARIO, CIDADE, UF, COD_DEPARTAMENTO)
VALUES ('Eduardo Pedro Henrique Almada ', '88079903859', 'eduardopedrohenriquealmada_@sprintrental.com.br ', '1987-02-11', 1, 'M', 1560, 'Monte Alto', 'SP', 4);
INSERT INTO FUNCIONARIO (NOME, CPF, EMAIL, DATA_NASCIMENTO, ATIVO, SEXO, SALARIO, CIDADE, UF, COD_DEPARTAMENTO)
VALUES ('Matheus Enrico Vicente Silva ', '48810010868', 'mmatheusenricovicentesilva@hormail.com ', '1989-03-12', 1, 'M', 1560, 'Monte Alto', 'SP', 4);
INSERT INTO FUNCIONARIO (NOME, CPF, EMAIL, DATA_NASCIMENTO, ATIVO, SEXO, SALARIO, CIDADE, UF, COD_DEPARTAMENTO)
VALUES ('Márcio Antonio Costa ', '72578974845', 'marcioantoniocosta-74@hotmmail.com ', '1999-04-13', 1, 'M', 7854, 'Monte Alto', 'SP', 4);
INSERT INTO FUNCIONARIO (NOME, CPF, EMAIL, DATA_NASCIMENTO, ATIVO, SEXO, SALARIO, CIDADE, UF, COD_DEPARTAMENTO)
VALUES ('Rafaela Eduarda Elaine Campos ', '46181779850', 'rafaelaeduardaelainecampos@ornatopresentes.com.br ', '2000-05-14', 1, 'F', 1560, 'Monte Alto', 'SP', 4);
INSERT INTO FUNCIONARIO (NOME, CPF, EMAIL, DATA_NASCIMENTO, ATIVO, SEXO, SALARIO, CIDADE, UF, COD_DEPARTAMENTO)
VALUES ('Daniel Carlos Davi Baptista ', '25251161867', 'danielcarlosdavibaptista@br.gestant.com ', '2001-09-15', 1, 'M', 1999, 'Catanduva', 'SP', 4);
INSERT INTO FUNCIONARIO (NOME, CPF, EMAIL, DATA_NASCIMENTO, ATIVO, SEXO, SALARIO, CIDADE, UF, COD_DEPARTAMENTO)
VALUES ('Melissa Lorena Gabrielly Nunes ', '38061688816', 'mmelissalorenagabriellynunes@msds.com.br ', '1981-07-16', 1, 'F', 1560, 'Catanduva', 'SP', 5);
INSERT INTO FUNCIONARIO (NOME, CPF, EMAIL, DATA_NASCIMENTO, ATIVO, SEXO, SALARIO, CIDADE, UF, COD_DEPARTAMENTO)
VALUES ('Gabrielly Marcela Sabrina Alves ', '38466243810', 'gabriellymarcelasabrinaalves-81@gap.com.br ', '1941-08-17', 1, 'F', 2220, 'Catanduva', 'SP', 5);
INSERT INTO FUNCIONARIO (NOME, CPF, EMAIL, DATA_NASCIMENTO, ATIVO, SEXO, SALARIO, CIDADE, UF, COD_DEPARTAMENTO)
VALUES ('Tereza Aparecida Alves ', '65673735804', 'tterezaaparecidaalves@unitau.com.br ', '1919-09-18', 1, 'F', 1560, 'Catanduva', 'SP', 6);
INSERT INTO FUNCIONARIO (NOME, CPF, EMAIL, DATA_NASCIMENTO, ATIVO, SEXO, SALARIO, CIDADE, UF, COD_DEPARTAMENTO)
VALUES ('Hadassa Vera dos Santos ', '12633855830', 'hadassaveradossantos_@prcondominios.com.br ', '1918-10-29', 1, 'F', 1100, 'Catanduva', 'SP', 6);
INSERT INTO FUNCIONARIO (NOME, CPF, EMAIL, DATA_NASCIMENTO, ATIVO, SEXO, SALARIO, CIDADE, UF, COD_DEPARTAMENTO)
VALUES ('Liz Eliane Rezende ', '20159352827', 'lizelianerezende@jotace.eti.br ', '1965-11-09', 1, 'F', 1560, 'Catanduva', 'SP', 7);

INSERT INTO PROJETO (NOME, DATA_INICIO, DATA_TERMINO, VALOR, COD_FUNC_GER)
VALUES ('S.I.C.', '2019-03-30', '2019-08-02', 53698.50, 18);
INSERT INTO PROJETO (NOME, DATA_INICIO, DATA_TERMINO, VALOR, COD_FUNC_GER)
VALUES ('SIGA', '2017-05-25', '2019-09-01', 40650.50, 18);
INSERT INTO PROJETO (NOME, DATA_INICIO, VALOR, COD_FUNC_GER)
VALUES ('C.G.A.', '2015-12-15', 25000, 18);
INSERT INTO PROJETO (NOME, DATA_INICIO, DATA_TERMINO, VALOR, COD_FUNC_GER)
VALUES ('JOOLMA', '2010-07-01', NULL, 69240.00, 15);
INSERT INTO PROJETO (NOME, DATA_INICIO, DATA_TERMINO, VALOR, COD_FUNC_GER)
VALUES ('WORDPRESS', '2017-01-25', NULL, 20123.00, 9);
INSERT INTO PROJETO (NOME, DATA_INICIO, DATA_TERMINO, VALOR, COD_FUNC_GER)
VALUES ('OJS', '2017-01-25', NULL, 20123.00, 9);
INSERT INTO PROJETO (NOME, DATA_INICIO, DATA_TERMINO, VALOR, COD_FUNC_GER)
VALUES ('FACEBOOK', '2017-01-25', NULL, 24123.00, 8);
INSERT INTO PROJETO (NOME, DATA_INICIO, DATA_TERMINO, VALOR, COD_FUNC_GER)
VALUES ('ORKUT', '2007-01-25', '2011-01-01', 20123.00, 9);
INSERT INTO PROJETO (NOME, DATA_INICIO, COD_FUNC_GER)
VALUES ('LINKEDIN', '2017-01-25', 10);
INSERT INTO PROJETO (NOME, DATA_INICIO, COD_FUNC_GER)
VALUES ('RJI', '2019-01-25', 10);
INSERT INTO PROJETO (NOME, DATA_INICIO, DATA_TERMINO, VALOR, COD_FUNC_GER)
VALUES ('CAKE', '2017-01-25', NULL, 20123.00, 9);
INSERT INTO PROJETO (NOME, DATA_INICIO, DATA_TERMINO, VALOR, COD_FUNC_GER)
VALUES ('CODEIGNITER', '2017-01-25', NULL, 24123.00, 8);
INSERT INTO PROJETO (NOME, DATA_INICIO, DATA_TERMINO, VALOR, COD_FUNC_GER)
VALUES ('NODE', '2007-01-25', '2011-01-01', 20123.00, 9);
INSERT INTO PROJETO (NOME, DATA_INICIO, COD_FUNC_GER)
VALUES ('JAVA', '2017-01-25', 9);
INSERT INTO PROJETO (NOME, DATA_INICIO, COD_FUNC_GER)
VALUES ('PHYTON', '2019-01-25', 9);

INSERT INTO FUNCIONARIO_PROJETO(DATA_ENTRADA, DATA_SAIDA, NUM_HORAS_TRAB, COD_FUNCIONARIO, COD_PROJETO)
VALUES ('2019-03-30', '2019-08-01', 20, 15, 14);
INSERT INTO FUNCIONARIO_PROJETO(DATA_ENTRADA, DATA_SAIDA, NUM_HORAS_TRAB, COD_FUNCIONARIO, COD_PROJETO)
VALUES ('2019-08-30', '2019-09-01', 20, 16, 14);
INSERT INTO FUNCIONARIO_PROJETO(DATA_ENTRADA, DATA_SAIDA, NUM_HORAS_TRAB, COD_FUNCIONARIO, COD_PROJETO)
VALUES ('2018-06-30', '2019-03-02', 20, 8, 14);
INSERT INTO FUNCIONARIO_PROJETO(DATA_ENTRADA, DATA_SAIDA, NUM_HORAS_TRAB, COD_FUNCIONARIO, COD_PROJETO)
VALUES ('2019-05-30', NULL, 20, 7, 6);
INSERT INTO FUNCIONARIO_PROJETO(DATA_ENTRADA, DATA_SAIDA, NUM_HORAS_TRAB, COD_FUNCIONARIO, COD_PROJETO)
VALUES ('2019-04-30', NULL, 20, 9, 6);
INSERT INTO FUNCIONARIO_PROJETO(DATA_ENTRADA, DATA_SAIDA, NUM_HORAS_TRAB, COD_FUNCIONARIO, COD_PROJETO)
VALUES ('2019-09-30', NULL, 20, 11, 6);
INSERT INTO FUNCIONARIO_PROJETO(DATA_ENTRADA, DATA_SAIDA, NUM_HORAS_TRAB, COD_FUNCIONARIO, COD_PROJETO)
VALUES ('2017-01-25', NULL, 15, 4, 5);
INSERT INTO FUNCIONARIO_PROJETO(DATA_ENTRADA, DATA_SAIDA, NUM_HORAS_TRAB, COD_FUNCIONARIO, COD_PROJETO)
VALUES ('2017-05-25', NULL, 15, 6, 5);
INSERT INTO FUNCIONARIO_PROJETO(DATA_ENTRADA, DATA_SAIDA, NUM_HORAS_TRAB, COD_FUNCIONARIO, COD_PROJETO)
VALUES ('2017-05-25', NULL, 15, 8, 5);
INSERT INTO FUNCIONARIO_PROJETO(DATA_ENTRADA, DATA_SAIDA, NUM_HORAS_TRAB, COD_FUNCIONARIO, COD_PROJETO)
VALUES ('2017-05-25', NULL, 15, 9, 5);
INSERT INTO FUNCIONARIO_PROJETO(DATA_ENTRADA, DATA_SAIDA, NUM_HORAS_TRAB, COD_FUNCIONARIO, COD_PROJETO)
VALUES ('2017-05-25', NULL, 15, 12, 5);
INSERT INTO FUNCIONARIO_PROJETO(DATA_ENTRADA, DATA_SAIDA, NUM_HORAS_TRAB, COD_FUNCIONARIO, COD_PROJETO)
VALUES ('2015-12-15', NULL, 26, 13, 6);
INSERT INTO FUNCIONARIO_PROJETO(DATA_ENTRADA, DATA_SAIDA, NUM_HORAS_TRAB, COD_FUNCIONARIO, COD_PROJETO)
VALUES ('2015-12-15', NULL, 26, 14, 6);
INSERT INTO FUNCIONARIO_PROJETO(DATA_ENTRADA, DATA_SAIDA, NUM_HORAS_TRAB, COD_FUNCIONARIO, COD_PROJETO)
VALUES ('2015-12-15', NULL, 26, 15, 6);
INSERT INTO FUNCIONARIO_PROJETO(DATA_ENTRADA, DATA_SAIDA, NUM_HORAS_TRAB, COD_FUNCIONARIO, COD_PROJETO)
VALUES ('2015-12-15', NULL, 26, 15, 7);
INSERT INTO FUNCIONARIO_PROJETO(DATA_ENTRADA, DATA_SAIDA, NUM_HORAS_TRAB, COD_FUNCIONARIO, COD_PROJETO)
VALUES ('2015-12-15', NULL, 26, 17, 7);
INSERT INTO FUNCIONARIO_PROJETO(DATA_ENTRADA, DATA_SAIDA, NUM_HORAS_TRAB, COD_FUNCIONARIO, COD_PROJETO)
VALUES ('2015-12-15', NULL, 26, 17, 8);
INSERT INTO FUNCIONARIO_PROJETO(DATA_ENTRADA, DATA_SAIDA, NUM_HORAS_TRAB, COD_FUNCIONARIO, COD_PROJETO)
VALUES ('2015-12-15', NULL, 26, 19, 8);
INSERT INTO FUNCIONARIO_PROJETO(DATA_ENTRADA, DATA_SAIDA, NUM_HORAS_TRAB, COD_FUNCIONARIO, COD_PROJETO)
VALUES ('2010-07-01', NULL, 50, 20, 9);
INSERT INTO FUNCIONARIO_PROJETO(DATA_ENTRADA, DATA_SAIDA, NUM_HORAS_TRAB, COD_FUNCIONARIO, COD_PROJETO)
VALUES ('2010-07-01', NULL, 50, 21, 9);
INSERT INTO FUNCIONARIO_PROJETO(DATA_ENTRADA, DATA_SAIDA, NUM_HORAS_TRAB, COD_FUNCIONARIO, COD_PROJETO)
VALUES ('2010-07-01', NULL, 50, 22, 9);
INSERT INTO FUNCIONARIO_PROJETO(DATA_ENTRADA, DATA_SAIDA, NUM_HORAS_TRAB, COD_FUNCIONARIO, COD_PROJETO)
VALUES ('2010-07-01', NULL, 50, 23, 9);
INSERT INTO FUNCIONARIO_PROJETO(DATA_ENTRADA, DATA_SAIDA, NUM_HORAS_TRAB, COD_FUNCIONARIO, COD_PROJETO)
VALUES ('2010-07-01', NULL, 50, 24, 9);
INSERT INTO FUNCIONARIO_PROJETO(DATA_ENTRADA, DATA_SAIDA, NUM_HORAS_TRAB, COD_FUNCIONARIO, COD_PROJETO)
VALUES ('2017-01-25', NULL, 80, 25, 10);

INSERT INTO DEPENDENTE (NOME, DATA_NASCIMENTO, PARENTESCO, COD_FUNCIONARIO)
VALUES ('Isis Nina Maya Moura', '2015-02-13', 'Filho', 3);
INSERT INTO DEPENDENTE (NOME, DATA_NASCIMENTO, PARENTESCO, COD_FUNCIONARIO)
VALUES ('Mirella Joana Cardoso', '2014-07-18', 'Filho', 3);
INSERT INTO DEPENDENTE (NOME, DATA_NASCIMENTO, PARENTESCO, COD_FUNCIONARIO)
VALUES ('Débora Vitória Cardoso', '2016-07-01', 'Filho', 3);
INSERT INTO DEPENDENTE (NOME, DATA_NASCIMENTO, PARENTESCO, COD_FUNCIONARIO)
VALUES ('Sônia Isis Cavalcanti', '2013-09-08', 'Filho', 5);
INSERT INTO DEPENDENTE (NOME, DATA_NASCIMENTO, PARENTESCO, COD_FUNCIONARIO)
VALUES ('Sérgio Ia Novaes', '2012-07-14', 'Filho', 5);
INSERT INTO DEPENDENTE (NOME, DATA_NASCIMENTO, PARENTESCO, COD_FUNCIONARIO)
VALUES ('Andreia Analu da Mota', '2016-05-08', 'Filho', 6);
INSERT INTO DEPENDENTE (NOME, DATA_NASCIMENTO, PARENTESCO, COD_FUNCIONARIO)
VALUES ('Vinicius Raul da Conceição', '2017-02-19', 'Filho', 20);
INSERT INTO DEPENDENTE (NOME, DATA_NASCIMENTO, PARENTESCO, COD_FUNCIONARIO)
VALUES ('Isabelle Teresinha Castro', '2018-11-05', 'Filho', 21);
INSERT INTO DEPENDENTE (NOME, DATA_NASCIMENTO, PARENTESCO, COD_FUNCIONARIO)
VALUES ('Vitor André Arthur dos Santos', '2015-07-14', 'Filho', 22);
INSERT INTO DEPENDENTE (NOME, DATA_NASCIMENTO, PARENTESCO, COD_FUNCIONARIO)
VALUES ('Leandro Benedito Noah Peixoto', '2016-05-22', 'Filho', 23);
INSERT INTO DEPENDENTE (NOME, DATA_NASCIMENTO, PARENTESCO, COD_FUNCIONARIO)
VALUES ('Louise Nina da Rocha', '2017-09-05', 'Filho', 13);
INSERT INTO DEPENDENTE (NOME, DATA_NASCIMENTO, PARENTESCO, COD_FUNCIONARIO)
VALUES ('Ester Olivia Barbosa', '2019-06-23', 'Filho', 17);
INSERT INTO DEPENDENTE (NOME, DATA_NASCIMENTO, PARENTESCO, COD_FUNCIONARIO)
VALUES ('Luciana Heloise Sabrina Silva', '2014-10-07', 'Filho', 19);
INSERT INTO DEPENDENTE (NOME, DATA_NASCIMENTO, PARENTESCO, COD_FUNCIONARIO)
VALUES ('Benedito Vicente Levi Viana', '2017-07-26', 'Filho', 3);
INSERT INTO DEPENDENTE (NOME, DATA_NASCIMENTO, PARENTESCO, COD_FUNCIONARIO)
VALUES ('Eloá Rebeca Vitória Monteiro', '2017-03-21', 'Filho', 5);
INSERT INTO DEPENDENTE (NOME, DATA_NASCIMENTO, PARENTESCO, COD_FUNCIONARIO)
VALUES ('Enzo Kauê Freitas', '2018-03-16', 'Filho', 8);
INSERT INTO DEPENDENTE (NOME, DATA_NASCIMENTO, PARENTESCO, COD_FUNCIONARIO)
VALUES ('Evelyn Vanessa Liz Novaes', '2018-08-26', 'Filho', 7);
INSERT INTO DEPENDENTE (NOME, DATA_NASCIMENTO, PARENTESCO, COD_FUNCIONARIO)
VALUES ('Sophia Caroline Heloisa Caldeira', '2017-07-10', 'Filho', 9);
INSERT INTO DEPENDENTE (NOME, DATA_NASCIMENTO, PARENTESCO, COD_FUNCIONARIO)
VALUES ('Isis Maya Simone Aparício', '2019-08-17', 'Filho', 9);
INSERT INTO DEPENDENTE (NOME, DATA_NASCIMENTO, PARENTESCO, COD_FUNCIONARIO)
VALUES ('Marina Brenda Raimunda Santos', '2016-12-19', 'Filho', 3);